apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: wordpress-deployment
  name: wordpress-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      run: wordpress
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        run: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
